import pygame

# screen/tile stuff
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
SCREEN_RECT = pygame.Rect(0,0,SCREEN_WIDTH,SCREEN_HEIGHT)
assert(SCREEN_WIDTH / SCREEN_HEIGHT == 16.0 / 9.0)
SCREEN_TILE_WIDTH = 16
SCREEN_TILE_HEIGHT = 9
TILE_WIDTH_PX = SCREEN_WIDTH // SCREEN_TILE_WIDTH
TILE_HEIGHT_PX = SCREEN_HEIGHT // SCREEN_TILE_HEIGHT

# colors
COLOR_BLACK = pygame.Color(0,0,0)
COLOR_BROWN = pygame.Color(101,67,33)
COLOR_GREEN = pygame.Color(34,139,34)

TILE_WALL_COLOR = COLOR_BROWN
TILE_FLOOR_COLOR = COLOR_GREEN

# player stuff
PLAYER_SPEED = 250
PLAYER_ANIM_FPS = 10.0 #fps
PLAYER_ANIM_SPF = 1 / PLAYER_ANIM_FPS