import pygame

WIDTH = 1600
HEIGHT = 900
assert(WIDTH / HEIGHT == 16.0 / 9.0)
SCREEN_TILE_WIDTH = 16
SCREEN_TILE_HEIGHT = 9
TILE_WIDTH_PX = WIDTH // SCREEN_TILE_WIDTH
TILE_HEIGHT_PX = HEIGHT // SCREEN_TILE_HEIGHT

COLOR_BLACK = pygame.Color(0,0,0)
COLOR_BROWN = pygame.Color(101,67,33)
COLOR_GREEN = pygame.Color(34,139,34)

TILE_WALL_COLOR = COLOR_BROWN
TILE_FLOOR_COLOR = COLOR_GREEN