import pygame


#screen stuff
WIDTH = 1200
HEIGHT = 960
FPS = 60


#color
COLOR_WHITE = (255, 255, 255)
COLOR_RED = (200, 0, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_CYAN = (0, 240, 225)
COLOR_YELLOW = (255, 255, 0)
COLOR_ORANGE = (255, 100, 0)
COLOR_TEAL = (125,249,255)
COLOR_MIDNIGHT_BLUE = (25,25,112)
COLOR_CORAL_RED = (255,64,64)
COLOR_GOLDENROD = (218,165,32)
COLOR_GREEN = (0, 255, 0)

#pieces
PIECES_SIZE = 140

#board stuff
COLUMN_COUNT = 15
ROW_COUNT = 10
X_EDGE_SPACING = 40
Y_EDGE_SPACING = 5
X_CIRCLE_SPACING = 2
Y_CIRCLE_SPACING = 2
CIRCLE_RADIUS_FROM_WIDTH = (WIDTH - (2 * X_EDGE_SPACING) - ((COLUMN_COUNT - 1) * X_CIRCLE_SPACING)) / 2 / COLUMN_COUNT
CIRCLE_RADIUS_FROM_HEIGHT = (HEIGHT - (2 * Y_EDGE_SPACING) - ((ROW_COUNT - 1) * Y_CIRCLE_SPACING)) / 2 / ROW_COUNT
if CIRCLE_RADIUS_FROM_WIDTH < CIRCLE_RADIUS_FROM_HEIGHT:
    CIRCLE_RADIUS = CIRCLE_RADIUS_FROM_WIDTH
    assert(WIDTH == (2 * X_EDGE_SPACING) + ((COLUMN_COUNT - 1) * X_CIRCLE_SPACING) + (COLUMN_COUNT * 2 * CIRCLE_RADIUS))
else:
    CIRCLE_RADIUS = CIRCLE_RADIUS_FROM_HEIGHT
    assert(HEIGHT == (2 * Y_EDGE_SPACING) + ((ROW_COUNT - 1) * Y_CIRCLE_SPACING) + (ROW_COUNT * 2 * CIRCLE_RADIUS))
