import pygame

# screen constants
WIDTH = 500
HEIGHT = 600
FPS = 60
pygame.font.init()
FONT = pygame.font.SysFont(None, 48)
pygame.display.set_caption("Dodge the Obstacle")

# COLORS
WHITE = (255, 255, 255)
RED = (200, 0, 0)
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
GREEN = (0, 240, 225)
YELLOW = (255, 255, 0)
ORANGE = (255, 100, 0)

# player stuff
PLAYER_MAX_HEALTH = 700

# obstacle stuff
OBS_FAST_CHANCE = 8
OBSTACLE_DMG_SMALL = 75
OBSTACLE_DMG_NORMAL = 100
OBSTACLE_DMG_BIG = 150
OBSTACLE_WIDTH = 20
OBSTACLE_HEIGHT = 30
OBSTACLE_SPEED_SMALL = 650
OBSTACLE_SPEED_NORMAL = 500
OBSTACLE_SPEED_BIG = 400
OBSTACLE_SPAWN_DELAY = 0.5
OBSTACLE_SIZE_SMALL = "small"
OBSTACLE_SIZE_NORMAL = "normal"
OBSTACLE_SIZE_BIG = "big"
OBSTACLE_SMALL_WIDTH = 14
OBSTACLE_SMALL_HEIGHT = 20
OBSTACLE_NORMAL_WIDTH = 20
OBSTACLE_NORMAL_HEIGHT = 30
OBSTACLE_BIG_WIDTH = 30
OBSTACLE_BIG_HEIGHT = 40
OBSTACLE_SPAWN_CHANCE = [
    OBSTACLE_SIZE_SMALL,
    OBSTACLE_SIZE_SMALL,
    OBSTACLE_SIZE_SMALL,
    OBSTACLE_SIZE_NORMAL,
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_BIG, 
    OBSTACLE_SIZE_BIG,
    OBSTACLE_SIZE_BIG
]

# HUD stuff
HEALTH_BAR_WIDTH = WIDTH
HEALTH_BAR_HEIGHT = 10
CHEAT_TIME_PREVENTION = 5
FILE_NAME = "leaderboard.txt"