import pygame
import random

# screen constants
WIDTH = 500
HEIGHT = 600
FPS = 60
pygame.font.init()
FONT_SIZE = 48
FONT = pygame.font.SysFont(None, FONT_SIZE)
pygame.display.set_caption("Dodge the Obstacle")

# COLORS
WHITE = (255, 255, 255)
RED = (200, 0, 0)
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
GREEN = (0, 240, 225)
YELLOW = (255, 255, 0)
ORANGE = (255, 100, 0)
TEAL = (125,249,255)
MIDNIGHT_BLUE = (25,25,112)
CORAL_RED = (255,64,64)

# player stuff
PLAYER_MAX_HEALTH = 1000

# obstacle stuff
OBS_FAST_CHANCE = 20
OBSTACLE_DMG_SMALL = 100
OBSTACLE_DMG_NORMAL = 150
OBSTACLE_DMG_BIG = 200
OBSTACLE_WIDTH = 20
OBSTACLE_HEIGHT = 30
OBSTACLE_SPEED_SMALL = 650
OBSTACLE_SPEED_NORMAL = 500
OBSTACLE_SPEED_BIG = 400
OBSTACLE_SPAWN_DELAY = 0.5
OBSTACLE_SIZE_SMALL = "small"
OBSTACLE_SIZE_NORMAL = "normal"
OBSTACLE_SIZE_BIG = "big"
OBSTACLE_SIZE_TRACKING = "tracking"
OBSTACLE_SMALL_WIDTH = 14
OBSTACLE_SMALL_HEIGHT = 20
OBSTACLE_NORMAL_WIDTH = 20
OBSTACLE_NORMAL_HEIGHT = 30
OBSTACLE_SPEED_TRACKING = random.randint(100, 275)
OBSTACLE_BIG_WIDTH = 30
OBSTACLE_BIG_HEIGHT = 40
OBSTACLE_SPAWN_CHANCE = [
    OBSTACLE_SIZE_SMALL,
    OBSTACLE_SIZE_SMALL,
    OBSTACLE_SIZE_SMALL,
    OBSTACLE_SIZE_NORMAL,
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_TRACKING,
    OBSTACLE_SIZE_TRACKING,
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_NORMAL, 
    OBSTACLE_SIZE_BIG, 
    OBSTACLE_SIZE_BIG,
    OBSTACLE_SIZE_BIG
]

# HUD stuff
HEALTH_BAR_WIDTH = WIDTH
HEALTH_BAR_HEIGHT = 10
CHEAT_TIME_PREVENTION = 5
FILE_NAME = "leaderboard.txt"

#power stuff
POWERUP_SPAWN_HEALTH_AMT = 0.5
POWERUP_SPAWN_DELAY = 30
HEALTH_BOOST_SPAWN_DELAY = 1
POWERUP_SPEED = 400
INVINCIBILITY_TIME = 5
HEALTH_POWERUP_SIZE = 20
HEALTH_BOOST_AMT = 175
INVINC_POWERUP_WIDTH = 20
INVINC_POWERUP_HEIGHT = 30