import pygame

# directions
DIR_UP = pygame.math.Vector2(0, -1)
DIR_DOWN = pygame.math.Vector2(0, 1)
DIR_LEFT = pygame.math.Vector2(-1, 0)
DIR_RIGHT = pygame.math.Vector2(1, 0)

#colors
COLOR_BLACK = (0,0,0)
COLOR_RED = (155,0,0)
COLOR_GREEN = (0,155,0)
COLOR_LAWN_GREEN = (124,252,0)
COLOR_CANDY_APPLE_RED = (226,6,44)
COLOR_DOGER_BLUE = (30,144,255)

# colors of things in the game
COLOR_BG = COLOR_LAWN_GREEN
COLOR_FOOD = COLOR_CANDY_APPLE_RED
COLOR_SNAKE = COLOR_DOGER_BLUE
COLOR_GRID = COLOR_LAWN_GREEN

# display
GRID_WIDTH = 160
GRID_HEIGHT = 90
EDGE_ZONE = 15
TILE_SIZE = 10
SCREEN_WIDTH = GRID_WIDTH * TILE_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * TILE_SIZE

#snake
SNAKE_WAIT_START = 0.0667
SNAKE_WAIT_MIN = 0.015